name: Build Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Docker version
        options:
          - php8.2-v1
          - php8.3-v1
  push:
    branches:
      - main
    paths:
      - "*/Dockerfile"
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.detected-versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detecting versions to build
        id: detected-versions
        run: |
          if [[ -v github.event.inputs.version ]]; then
            echo 'versions=["${github.event.inputs.version}"]' >> $GITHUB_OUTPUT;
          else
            echo "git diff"
            echo $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
            v=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep "^php.*/Dockerfile$" | xargs -r dirname)
            echo "changed versions after filter"
            echo "$v"
            echo "writing into versions..."
            echo 'versions=$(echo "$v" | jq --raw-input | jq --slurp | xargs echo)' >> $GITHUB_OUTPUT;
          fi

  build:
    name: Build & push docker images
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        versions: ${{ fromJson(needs.setup.outputs.versions) }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          echo "$password" | docker login --username $username --password-stdin
      - name: Build the docker image
        id: build-docker-image
        run: echo steps.detected-versions.outputs.versions | xargs -I {} docker build . -f {}/Dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/thepay-environment:{}
      - name: Push the docker image
        id: push-docker-image
        run: echo steps.detected-versions.outputs.versions | xargs -I {} docker push ${{secrets.DOCKERHUB_USERNAME}}/thepay-environment:{}
      - name: Logout from docker hub & clear credentials
        run: |
          docker logout
          rm $HOME/.docker/config.json
