name: Build Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Docker version
        options:
          - php8.2-v1
          - php8.3-v1
  push:
    branches:
      - main
    paths:
      - "*/Dockerfile"
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      matrix-set-as-json: ${{ steps.detect-versions.outputs.out }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detecting versions to build
        id: detect-versions
        run: |
          if [[ "${{ github.event.inputs.version }}" != "" ]]; then
          echo "versions detected by input"\
          && VERSIONS=$(echo ${{ github.event.inputs.version }} | jq --raw-input | jq --slurp)
          else
          echo "versions detected by changelog"\
          && VERSIONS=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} \
            | grep "^php.*/Dockerfile$"\
            | xargs -r dirname\
            | jq --raw-input\
            | jq --slurp\
          )
          fi
          echo "out=$(jq -cn --argjson versions "$VERSIONS" '{version: $versions}')"
          echo "out=$(jq -cn --argjson versions "$VERSIONS" '{version: $versions}')" >> $GITHUB_OUTPUT

  build:
    name: Build & push docker images
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix-set-as-json) }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          echo "$password" | docker login --username $username --password-stdin
      - name: Build the docker image
        id: build-docker-image
        run: docker build . -f ${{ matrix.version }}/Dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/thepay-environment:${{ matrix.version }}
      - name: Push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/thepay-environment:${{ matrix.version }}
      - name: Logout from docker hub & clear credentials
        run: |
          docker logout
          rm $HOME/.docker/config.json
