name: Build Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Docker version
        options:
          - php8.2-v1
          - php8.3-v1
  push:
    branches:
      - main
    paths:
      - "*/Dockerfile"
      - ".github/workflows/build.yml"
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            ref: main

        - name: Detecting versions to build
          id: detected-versions
          run: |
            echo ${git diff origin/main}
            echo "versions=$(if [[ -v inputs.version ]]; then echo "${inputs.version}"; else git diff origin/main --name-only | grep "php.*/Dockerfile" | xargs -r dirname | uniq | echo; fi)" >> $GITHUB_OUTPUT

        - name: Login to docker hub
          if: steps.detected-versions.outputs.versions
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            echo "$password" | docker login --username $username --password-stdin
        - name: Build the docker image
          if: steps.detected-versions.outputs.versions
          id: build-docker-image
          run: echo steps.detected-versions.outputs.versions | xargs -I {} docker build . -f {}/Dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/thepay-environment:{}
        - name: Push the docker image
          if: steps.detected-versions.outputs.versions
          id: push-docker-image
          run: echo steps.detected-versions.outputs.versions | xargs -I {} docker push ${{secrets.DOCKERHUB_USERNAME}}/thepay-environment:{}
        - name: Logout from docker hub & clear credentials
          if: steps.detected-versions.outputs.versions
          run: |
            docker logout
            rm $HOME/.docker/config.json
