name: Build Docker Image
on:
  push:
    branches:
      - main
    paths:
      - "./Dockerfile"
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            echo "$password" | docker login --username $username --password-stdin
        - name: Build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/thepay-environment:latest
        - name: Push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/thepay-environment:latest
        - name: Logout from docker hub & clear credentials
          run: |
            docker logout
            rm $HOME/.docker/config.json
